"""
models.py - SQLAlchemy ORM Database Models

This file defines every database table used by the IMAMU Course Scheduler as
Python classes (SQLAlchemy ORM models). Each class maps to one database table,
and each class attribute maps to a column in that table.

Tables defined here:
  - users                   : Student, instructor, and admin accounts.
  - departments             : Academic departments (e.g. "Computer Science").
  - courses                 : University courses offered by departments.
  - instructors             : Teaching staff and their workload limits.
  - rooms                   : Physical classrooms / labs and their capacity.
  - time_slots              : Discrete class periods in a day (e.g. 08:00-09:00).
  - days                    : Days of the week the university operates.
  - sections                : Individual class sections (a course can have many).
  - saved_schedules         : Schedules generated by the algorithm and saved by users.
  - course_prerequisites    : Many-to-many link between courses and their prerequisites.
  - student_completed_courses: Many-to-many link tracking which courses a student has passed.
  - student_registrations   : Many-to-many link tracking which sections a student is enrolled in.
"""

from sqlalchemy import (
    Column, Integer, String, Boolean, Float, ForeignKey, Table, Text,
    UniqueConstraint, Enum as SAEnum
)
from sqlalchemy.orm import relationship
import enum
from app.database import Base


# ---------------------------------------------------------------------------
# Enum: User roles
# ---------------------------------------------------------------------------
class UserRole(str, enum.Enum):
    """
    Defines the three possible roles a user can have in the system.
    Inheriting from `str` lets the enum serialize to JSON automatically.
    """
    STUDENT = "student"
    INSTRUCTOR = "instructor"
    ADMIN = "admin"


# ===========================================================================
# Association (junction) tables for many-to-many relationships
# ===========================================================================
# These tables don't have their own ORM class because they only store pairs
# of foreign keys. SQLAlchemy manages them through the `relationship(...,
# secondary=...)` parameter on the related models.

# Links a course to its prerequisite courses.
# Example: "Data Structures" requires "Intro to Programming".
course_prerequisites = Table(
    "course_prerequisites",
    Base.metadata,
    Column("course_id", Integer, ForeignKey("courses.id"), primary_key=True),
    Column("prerequisite_id", Integer, ForeignKey("courses.id"), primary_key=True),
)

# Tracks which courses a student has already completed (passed).
# Used to verify prerequisite requirements during registration.
student_completed_courses = Table(
    "student_completed_courses",
    Base.metadata,
    Column("user_id", Integer, ForeignKey("users.id"), primary_key=True),
    Column("course_id", Integer, ForeignKey("courses.id"), primary_key=True),
)

# Tracks which sections a student is currently registered (enrolled) in.
student_registrations = Table(
    "student_registrations",
    Base.metadata,
    Column("user_id", Integer, ForeignKey("users.id"), primary_key=True),
    Column("section_id", Integer, ForeignKey("sections.id"), primary_key=True),
)


# ===========================================================================
# ORM Model Classes
# ===========================================================================

class User(Base):
    """
    Represents a user account (student, instructor, or admin).

    Relationships:
      - completed_courses  : Courses the student has passed (many-to-many via
                             student_completed_courses).
      - registered_sections: Sections the student is currently enrolled in
                             (many-to-many via student_registrations).
      - saved_schedules    : Schedules the user has generated and saved.
    """
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String(100), unique=True, index=True, nullable=False)
    email = Column(String(255), unique=True, index=True, nullable=False)
    hashed_password = Column(String(255), nullable=False)       # Bcrypt hash, never plain text
    full_name = Column(String(255), nullable=False)
    role = Column(SAEnum(UserRole), nullable=False, default=UserRole.STUDENT)
    gender = Column(String(10), default="Male")                 # Used for gender-separated scheduling
    department = Column(String(100), default="")
    level = Column(Integer, default=1)                          # Academic year / level (1-8+)
    is_active = Column(Boolean, default=True)                   # Soft-delete flag

    # Many-to-many: courses this student has completed
    completed_courses = relationship("Course", secondary=student_completed_courses, backref="completed_by")
    # Many-to-many: sections this student is registered in
    registered_sections = relationship("Section", secondary=student_registrations, backref="registered_students")
    # One-to-many: schedules saved by this user
    saved_schedules = relationship("SavedSchedule", back_populates="user")


class Department(Base):
    """
    An academic department (e.g. "Computer Science", "Mathematics").
    Each department has a unique short code (e.g. "CS", "MATH") and contains
    many courses.
    """
    __tablename__ = "departments"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), unique=True, nullable=False)     # Full name, e.g. "Computer Science"
    code = Column(String(10), unique=True, nullable=False)      # Short code, e.g. "CS"

    # One-to-many: all courses that belong to this department
    courses = relationship("Course", back_populates="department")


class Course(Base):
    """
    A university course (e.g. "CS 101 - Introduction to Programming").

    Relationships:
      - department    : The department offering this course.
      - sections      : The individual sections (class groups) for this course.
      - prerequisites : Other Course objects that must be completed before a
                        student can register. This is a self-referential
                        many-to-many relationship through course_prerequisites.
    """
    __tablename__ = "courses"

    id = Column(Integer, primary_key=True, index=True)
    code = Column(String(20), unique=True, nullable=False, index=True)  # e.g. "CS101"
    name = Column(String(255), nullable=False)                          # e.g. "Intro to Programming"
    level = Column(Integer, default=1)                                  # Target academic level
    credits = Column(Integer, default=3)                                # Credit hours
    is_lab = Column(Boolean, default=False)                             # True if this is a lab course
    is_archived = Column(Boolean, default=False)                        # Hidden from active listings
    department_id = Column(Integer, ForeignKey("departments.id"))       # FK to departments table

    department = relationship("Department", back_populates="courses")
    # Cascade delete: removing a course also removes its sections
    sections = relationship("Section", back_populates="course", cascade="all, delete-orphan")

    # Self-referential many-to-many: prerequisite courses
    # primaryjoin: "this course" side; secondaryjoin: "prerequisite" side
    prerequisites = relationship(
        "Course",
        secondary=course_prerequisites,
        primaryjoin=id == course_prerequisites.c.course_id,
        secondaryjoin=id == course_prerequisites.c.prerequisite_id,
        backref="required_by",  # Reverse: courses that require *this* course
    )


class Instructor(Base):
    """
    A teaching staff member. Stores personal info and weekly teaching-hour
    limits used by the scheduling algorithm to avoid overloading instructors.
    """
    __tablename__ = "instructors"

    id = Column(Integer, primary_key=True, index=True)
    instructor_id = Column(String(20), unique=True, nullable=False)  # University staff ID
    name = Column(String(255), nullable=False)
    gender = Column(String(10), default="Male")
    department = Column(String(100), default="")
    rank = Column(String(50), default="")           # Academic rank (e.g. "Professor", "Lecturer")
    min_hours = Column(Integer, default=12)          # Minimum weekly teaching hours
    max_hours = Column(Integer, default=18)          # Maximum weekly teaching hours


class Room(Base):
    """
    A physical classroom or lab where classes can be held.
    Includes capacity and type information used by the scheduling algorithm
    to assign rooms that fit the section size and course requirements.
    """
    __tablename__ = "rooms"

    id = Column(Integer, primary_key=True, index=True)
    room_id = Column(String(20), unique=True, nullable=False)    # Room number/code (e.g. "B2-101")
    capacity = Column(Integer, default=40)                       # Maximum number of students
    gender = Column(String(10), default="")                      # Gender restriction, if any
    room_type = Column(String(50), default="Lecture Hall")       # "Lecture Hall", "Lab", etc.
    floor = Column(Integer, default=1)
    building = Column(String(100), default="")
    equipment = Column(String(255), default="")                  # Available equipment (projector, etc.)


class TimeSlot(Base):
    """
    A discrete period during the day when a class can be scheduled
    (e.g. "Period 1: 08:00 - 09:00").

    slot_order is used to sort time slots chronologically in the UI and
    scheduling algorithm.
    """
    __tablename__ = "time_slots"

    id = Column(Integer, primary_key=True, index=True)
    label = Column(String(20), unique=True, nullable=False)      # Display label (e.g. "P1")
    start_time = Column(String(10), nullable=False)              # e.g. "08:00"
    end_time = Column(String(10), nullable=False)                # e.g. "09:00"
    slot_type = Column(String(10), default="Class")              # "Class" or "Break"
    slot_order = Column(Integer, default=0)                      # Sort order (0 = earliest)


class Day(Base):
    """
    A day of the week that the university operates on.
    Imported from the XML seed data (e.g. code="SUN", name="Sunday").
    """
    __tablename__ = "days"

    id = Column(Integer, primary_key=True, index=True)
    code = Column(String(5), unique=True, nullable=False)        # Short code (e.g. "SUN", "MON")
    name = Column(String(20), default="")                        # Full name (e.g. "Sunday")


class Section(Base):
    """
    A specific section (class group) of a course. A single course like "CS101"
    can have multiple sections (e.g. "CS101-M1" for males, "CS101-F1" for females).

    The `enrolled` field tracks how many students are currently registered,
    and `capacity` is the maximum allowed.
    """
    __tablename__ = "sections"

    id = Column(Integer, primary_key=True, index=True)
    section_id = Column(String(20), unique=True, nullable=False)  # e.g. "CS101-M1"
    gender = Column(String(10), default="Male")                   # Gender restriction for this section
    capacity = Column(Integer, default=40)                        # Max students allowed
    enrolled = Column(Integer, default=0)                         # Current enrollment count
    course_id = Column(Integer, ForeignKey("courses.id"))         # FK to the parent course
    is_archived = Column(Boolean, default=False)                  # Hidden from active listings

    # Many-to-one: the course this section belongs to
    course = relationship("Course", back_populates="sections")


class SavedSchedule(Base):
    """
    A generated timetable that a user chose to save. Stores the algorithm
    used, fitness score, conflict count, and the full schedule as a JSON
    string in schedule_data.
    """
    __tablename__ = "saved_schedules"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))            # The user who saved this schedule
    name = Column(String(255), default="My Schedule")            # User-given name
    algorithm = Column(String(10), default="GA")                 # Algorithm used: "GA" (Genetic), etc.
    objective = Column(String(20), default="student")            # Optimization objective
    fitness = Column(Float, default=0.0)                         # Quality score (higher = better)
    conflicts = Column(Float, default=0.0)                       # Number/score of scheduling conflicts
    schedule_data = Column(Text, nullable=False)                 # Full schedule stored as JSON string

    # Many-to-one: the user who owns this saved schedule
    user = relationship("User", back_populates="saved_schedules")
